services:
  postgres:
    image: postgres:17
    container_name: devtrack-postgres
    environment:
      POSTGRES_USER: devtrack
      POSTGRES_PASSWORD: devtrack
      POSTGRES_DB: devtrack
    ports:
      - "5433:5432"
    volumes:
      - devtrack_postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: always
    ports: 
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=my_pass
    command: redis-server --requirepass my_pass
  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  devtrack_postgres_data:
  redis_data: