"""added team_member model

Revision ID: ccddbde43203
Revises: 8d54e80ca809
Create Date: 2026-06-30 19:12:04.428772

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ccddbde43203"
down_revision: Union[str, Sequence[str], None] = "8d54e80ca809"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Обновление схемы."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "OWNER",
                "ADMIN",
                "DEVELOPER",
                "VIEWER",
                "INTERN",
                "MANAGER",
                "DESIGNER",
                "QA",
                name="team_role",
            ),
            nullable=False,
        ),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id", "user_id", name="uq_team_member"),
    )
    op.create_index(
        op.f("ix_team_members_team_id"), "team_members", ["team_id"], unique=False
    )
    op.create_index(
        op.f("ix_team_members_user_id"), "team_members", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Откат схемы."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_team_members_user_id"), table_name="team_members")
    op.drop_index(op.f("ix_team_members_team_id"), table_name="team_members")
    op.drop_table("team_members")
    # ### end Alembic commands ###
