"""Доменные исключения, которые использует task service и обработчики API."""

class TaskError(Exception):
    ...

class TaskNotFoundError(TaskError):
    ...

class TaskPermissionError(TaskError):
    ...

class InvalidPaginationError(TaskError):
    ...
